[workspace]
members = [
    "src/cashier_backend", 
    "src/lib/cashier-macros",
    "src/token_storage",
    "src/lib/cashier-types"
]
resolver = "2"

[workspace.dependencies]
candid = "0.10.14"
ic-cdk = "0.18.4"
ic-stable-structures = "0.6.9"
ic-cdk-timers = "0.12.1"
ic-icrc-tx = "0.1.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
getrandom = { version = "0.2", features = ["custom"] }
rand = { version = "0.8.5", features = ["getrandom"]}
uuid = {version = "1.10.0", features = [ "v4" ]}
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"
serde_bytes = "0.11.15"
itertools = "0.13.0"
icrc-ledger-types = "0.1.10"
base64 = "0.22.1"
rm = "0.3.2"
serde_cbor = "0.11.2"
tokio = { version = "1", features = ["rt", "macros"] }


