[workspace]
members = [
    "src/cashier_backend",
    "src/lib/cashier-macros",
    "src/token_storage",
    "src/lib/cashier-types",
    "src/integration_tests",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1"
base64 = "0.22"
candid = "0.10"
cashier-macros = { path = "src/lib/cashier-macros" }
cashier-types = { path = "src/lib/cashier-types" }
futures = { version = "0.3", default-features = false }
getrandom = { version = "0.2", features = ["custom"] }
ic-cdk = "0.18"
ic-cdk-timers = "0.12"
ic-icrc-tx = "0.1"
ic-stable-structures = "0.6"
ic_mple_pocket_ic = "0.7"
icrc-ledger-types = "0.1"
itertools = "0.14"
proc-macro2 = "1.0"
quote = "1.0"
rand = { version = "0.8", features = ["getrandom"] }
rm = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_json = "1.0"
syn = "2.0"
thiserror = "2.0"
tokio = { version = "1", features = ["rt", "macros"] }
# Use fixed uuid version to avoid getrandom incompatibility. To be fixed.
uuid = { version = "=1.12.1", features = ["v4"] }
