[package]
name = "gate_service_client"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
candid = { workspace = true }
cashier_common = { workspace = true }
gate_service_types = { workspace = true }
ic_mple_client = { workspace = true }
