[package]
name = "integration_tests"
version.workspace = true
edition.workspace = true
license.workspace = true


[dev-dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic_mple_pocket_ic = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
