[package]
name = "gate_service_types"
version = "0.1.0"
edition = "2024"

[dependencies]
candid = { workspace = true }
cashier_macros = { workspace = true }
ic-cdk = { workspace = true }
ic-stable-structures = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
